export const Day = {
		0:'Sunday',
		1: 'Monday',
		2: 'Tuesday',
		3: 'Wednesday',
		4: 'Thursday',
		5: 'Friday',
		6: 'Saturday',
		7: 'Sunday',
		8: 'Monday',
		9: 'Tuesday',
		10: 'Wednesday',
		11: 'Thursday',
		12: 'Friday',
		13: 'Saturday',
		14:'Sunday',
		15: 'Monday',
};
